apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      containers:
        - name: java-k8s-app
          image: yourdockerhub/java-k8s-app
          ports:
            - containerPort: 8080